apiVersion: apps/v1
kind: Deployment
metadata:
  name: books
spec:
  replicas: 1
  selector:
    matchLabels:
      app-name: books-app
  template:
    metadata:
      labels:
        app-name: books-app
    spec:
      containers:
        - name: books
          image: landrzejewski/books-v2
---
apiVersion: v1
kind: Service
metadata:
  name: books-service
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30666
  selector:
    app-name: books-app