apiVersion: batch/v1
kind: Job
metadata:
  name: long-task-jo
spec:
  completions: 3
  parallelism: 2
  activeDeadlineSeconds: 300
  ttlSecondsAfterFinished: 180
  template:
    metadata:
      labels:
         app-name: long-task
    spec:
      restartPolicy: OnFailure
      containers:
        - image: landrzejewski/long-task:v1
          name: long-task
