apiVersion: v1
kind: PersistentVolume
metadata:
  name: share
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
    - ReadOnlyMany
  hostPath:
    path: /tmp/share
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: share-claim
spec:
  resources:
    requests:
      storage: 1Gi
  accessModes:
    - ReadWriteOnce
---
apiVersion: v1
kind: Pod
metadata:
  name: books
  labels:
    app-name: books
spec:
  nodeSelector:
    nodeName: master
  containers:
    - name: nginx
      image: nginx:alpine
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: content
          readOnly: true
  volumes:
    - name: content
      persistentVolumeClaim:
        claimName: share-claim
---
apiVersion: v1
kind: Service
metadata:
  name: books-service
spec:
  type: NodePort
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30555
  selector:
    app-name: books
