apiVersion: v1
kind: Pod
metadata:
  name: updater-po
spec:
  containers:
    - image: nginx:1.15.9-alpine
      name: web-server
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: content
          readOnly: true
  volumes:
    - name: content
      gitRepo:
        repository: https://github.com/landrzejewski/spring-training
        revision: master
        directory: .
