apiVersion: v1
kind: Pod
metadata:
  name: updater-po
spec:
  containers:
    - image: landrzejewski/updater:v2
      name: generator
      volumeMounts:
        - mountPath: /var/htdocs
          name: content
        - mountPath: /config
          name: config
      #args:
      #  - '20'

      #env:
      #  - name: INTERVAL
      #    value: '20'

      #env:
      #  - name: INTERVAL
      #    valueFrom:
      #      configMapKeyRef:
      #        name: updater-cm
      #        key: sleep-interval

      envFrom:
        - configMapRef:
            name: updater-cm

    - image: nginx:1.15.9-alpine
      name: web-server
      ports:
        - containerPort: 80
      volumeMounts:
        - mountPath: /usr/share/nginx/html
          name: content
  volumes:
    - name: content
      emptyDir:
        medium: Memory
    - name: config
      configMap:
        name: updater-config
